In [28]:
import pandas as pd
import numpy as np
from scipy.stats import chisquare

First we'll save the 'counts' dataframe as its own csv, replacing all the 0s with ones, for some reason. This python code was taken from GO_term_analysis.py

In [51]:
#Save counts as its own csv, create chi-square values
counts = pd.read_csv('htseq_counts_stranded_reverse.txt', sep='\t')
counts = counts.replace(to_replace=0, value=1)

,Gene,AF16_Control,Gene_2,AF16_Treatment,Gene_3,HK104_Control,Gene_4,HK104_Treatment,AF_sum,HK_sum,control_sum,treatment_sum,AFHK_sum,AF_control_exp,AF_treatment_exp,HK_control_exp,HK_treatment_exp,test_value
0,WBGene00000307,446,WBGene00000307,319,WBGene00000307,472,WBGene00000307,453,765,925,918,772,1690,415.544379,349.455621,502.455621,422.544379,1
1,WBGene00000312,9,WBGene00000312,8,WBGene00000312,11,WBGene00000312,3,17,14,20,11,31,10.967742,6.032258,9.032258,4.967742,1
2,WBGene00000324,21,WBGene00000324,16,WBGene00000324,24,WBGene00000324,5,37,29,45,21,66,25.227273,11.772727,19.772727,9.227273,1
3,WBGene00000328,490,WBGene00000328,626,WBGene00000328,448,WBGene00000328,478,1116,926,938,1104,2042,512.638590,603.361410,425.361410,500.638590,1
4,WBGene00000329,222,WBGene00000329,148,WBGene00000329,203,WBGene00000329,165,370,368,425,313,738,213.075881,156.924119,211.924119,156.075881,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23139,WBGene00304769,1,WBGene00304769,1,WBGene00304769,1,WBGene00304769,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23140,WBGene00304770,1,WBGene00304770,1,WBGene00304770,1,WBGene00304770,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23141,WBGene00304771,1,WBGene00304771,1,WBGene00304771,1,WBGene00304771,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23142,WBGene00304772,1,WBGene00304772,1,WBGene00304772,1,WBGene00304772,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23143,WBGene00304773,1,WBGene00304773,1,WBGene00304773,1,WBGene00304773,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0

Now we'll do a chi square test (this one: https://www.khanacademy.org/math/ap-statistics/chi-square-tests/chi-square-tests-two-way-tables/v/chi-square-test-association-independence) on the values. The test_value column specifies whether or not the log2(chi-square value) is greater than 0.

In [52]:
counts['AF_sum'] = counts['AF16_Control'] + counts['AF16_Treatment']
counts['HK_sum'] = counts['HK104_Control'] + counts['HK104_Treatment']
counts['control_sum'] = counts['AF16_Control'] + counts['HK104_Control']
counts['treatment_sum'] = counts['AF16_Treatment'] + counts['HK104_Treatment']
counts['AFHK_sum'] = counts['AF_sum'] + counts['HK_sum']
counts['AF_control_exp'] = (counts['control_sum'] / counts['AFHK_sum'])*(counts['AF_sum'] / counts['AFHK_sum']) * counts['AFHK_sum']
counts['AF_treatment_exp'] = (counts['treatment_sum'] / counts['AFHK_sum'])*(counts['AF_sum'] / counts['AFHK_sum']) * counts['AFHK_sum']
counts['HK_control_exp'] = (counts['control_sum'] / counts['AFHK_sum'])*(counts['HK_sum'] / counts['AFHK_sum']) * counts['AFHK_sum']
counts['HK_treatment_exp'] = (counts['treatment_sum'] / counts['AFHK_sum'])*(counts['HK_sum'] / counts['AFHK_sum']) * counts['AFHK_sum']
counts['test_value'] = (counts['AF16_Control'] - counts["AF_control_exp"]) ** 2 / counts['AF_control_exp']
counts['test_value'] += (counts['AF16_Treatment'] - counts["AF_treatment_exp"]) ** 2 / counts['AF_treatment_exp']
counts['test_value'] += (counts['HK104_Treatment'] - counts["HK_treatment_exp"]) ** 2 / counts['HK_treatment_exp']
counts['test_value'] += (counts['HK104_Control'] - counts["HK_control_exp"]) ** 2 / counts['HK_control_exp']

counts['test_value'] = np.log2(counts["test_value"])
counts['test_value'] = counts['test_value'] > 0
counts['test_value'] = counts['test_value'].astype(int)
counts

,Gene,AF16_Control,Gene_2,AF16_Treatment,Gene_3,HK104_Control,Gene_4,HK104_Treatment,AF_sum,HK_sum,control_sum,treatment_sum,AFHK_sum,AF_control_exp,AF_treatment_exp,HK_control_exp,HK_treatment_exp,test_value
0,WBGene00000307,446,WBGene00000307,319,WBGene00000307,472,WBGene00000307,453,765,925,918,772,1690,415.544379,349.455621,502.455621,422.544379,1
1,WBGene00000312,9,WBGene00000312,8,WBGene00000312,11,WBGene00000312,3,17,14,20,11,31,10.967742,6.032258,9.032258,4.967742,1
2,WBGene00000324,21,WBGene00000324,16,WBGene00000324,24,WBGene00000324,5,37,29,45,21,66,25.227273,11.772727,19.772727,9.227273,1
3,WBGene00000328,490,WBGene00000328,626,WBGene00000328,448,WBGene00000328,478,1116,926,938,1104,2042,512.638590,603.361410,425.361410,500.638590,1
4,WBGene00000329,222,WBGene00000329,148,WBGene00000329,203,WBGene00000329,165,370,368,425,313,738,213.075881,156.924119,211.924119,156.075881,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23139,WBGene00304769,1,WBGene00304769,1,WBGene00304769,1,WBGene00304769,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23140,WBGene00304770,1,WBGene00304770,1,WBGene00304770,1,WBGene00304770,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23141,WBGene00304771,1,WBGene00304771,1,WBGene00304771,1,WBGene00304771,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23142,WBGene00304772,1,WBGene00304772,1,WBGene00304772,1,WBGene00304772,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0
23143,WBGene00304773,1,WBGene00304773,1,WBGene00304773,1,WBGene00304773,1,2,2,2,2,4,1.000000,1.000000,1.000000,1.000000,0

Now we can load all the relevant data into pandas dataframes. In the below cell we'll load what was the 'counts' dataframe into experiment, and clean it up. We'll use only the gene name, control, and treatment values, and drop all the other columns. I divided control by treatment, took the absolute value, and stuck that in the test_value column.

In [53]:
experiment = pd.read_csv('experimental_data.csv')

experiment = experiment[['Gene', 'log2foldchange_control', 'log2foldchange_treatment']].copy()
experiment = experiment.rename({'log2foldchange_control': 'control', 'log2foldchange_treatment':'treatment'}, axis=1)
experiment['test_value'] = np.abs(experiment['control'] / experiment['treatment'])
experiment

                 Gene   control  treatment  test_value
0      WBGene00000307 -0.081743  -0.505955    0.161562
1      WBGene00000312 -0.289507   1.415037    0.204593
2      WBGene00000324 -0.192645   1.678072    0.114801
3      WBGene00000328  0.129283   0.389152    0.332217
4      WBGene00000329  0.129080  -0.156869    0.822853
...               ...       ...        ...         ...
14138  WBGene00304233 -2.321928  -3.584963    0.647685
14139  WBGene00304234 -0.304855   0.917538    0.332253
14140  WBGene00304757  0.241008   0.961526    0.250652
14141  WBGene00304763  2.321928   0.000000         inf
14142  WBGene00304765  0.565726   0.772823    0.732026

[14143 rows x 4 columns]

Now we'll load 'GO_terms_no_dups.txt' into the df go_genes. I parsed it so that in the 'genes' column I have a list of all the genes corresponding to that particular go squence.

In [54]:
go_genes = pd.read_csv('briggsae_GO_terms_no_dups.txt',sep='\t')
go_genes = go_genes.rename({go_genes.columns[0]:'go_sequence',
                            go_genes.columns[1]:'genes'}, axis=1)
go_genes

             go_sequence                                              genes
0             GO:0000003  WBGene00023826,WBGene00024356,WBGene00024943,W...
1             GO:0000012                                     WBGene00041049
2             GO:0000019                                     WBGene00035859
3             GO:0000022                                     WBGene00026971
4             GO:0000027  WBGene00023936,WBGene00024087,WBGene00024572,W...
...                  ...                                                ...
2877          GO:2001255                                     WBGene00033437
2878          GO:2001256                                     WBGene00025899
2879          GO:2001258                                     WBGene00036655
2880          GO:2001294                                     WBGene00037538
2881  biological_process  Pyrimidine nucleotide-sugars are pyrimidine nu...

[2882 rows x 2 columns]

Now we're going to remove all genes in experiment that don't have a go_sequence.

In [55]:
def find_my_GO(string):
    t = go_genes.loc[go_genes['genes'].str.contains(string)]
    return t['go_sequence'].str.cat(sep=',')

experiment['go_sequences'] = np.vectorize(find_my_GO)(experiment['Gene'])

In [56]:
experiment = experiment.loc[experiment['go_sequences'] != '']
experiment = experiment.loc[experiment['test_value'] == experiment['test_value']]
experiment

,Gene,control,treatment,test_value,go_sequences
1,WBGene00000312,-0.289507,1.415037,0.204593,"GO:0008150,GO:0015671"
2,WBGene00000324,-0.192645,1.678072,0.114801,"GO:0006811,GO:0006813,GO:0051260,GO:0055085"
3,WBGene00000328,0.129283,0.389152,0.332217,GO:0006470
4,WBGene00000329,0.129080,-0.156869,0.822853,"GO:0007275,GO:0007283,GO:0007548,GO:0010628,GO..."
5,WBGene00000332,0.217002,0.072512,2.992621,"GO:0006006,GO:0006096,GO:0055114"
...,...,...,...,...,...
14069,WBGene00303306,4.990955,2.392317,2.086243,GO:0006468
14088,WBGene00303376,1.000000,1.514573,0.660252,"GO:0007155,GO:0007156"
14111,WBGene00303438,-0.082305,-0.020122,4.090396,"GO:0006465,GO:0006508,GO:0006627"
14122,WBGene00304200,0.145648,0.093109,1.564263,GO:0006468
14142,WBGene00304765,0.565726,0.772823,0.732026,GO:0006355

In [57]:
def count_genes(go_seq):
    t = experiment.loc[experiment['go_sequences'].str.contains(go_seq)]
    
    return t.shape[0]
    
go_genes['count'] = np.vectorize(count_genes)(go_genes['go_sequence'])
go_genes = go_genes.iloc[:2881, :].copy()

go_genes = go_genes.loc[go_genes['count'] != 0]

Now we add the p values.

In [58]:
def test_sum(go_seq):
    t = experiment.loc[experiment['go_sequences'].str.contains(go_seq)]
    return np.mean(t['test_value'])

go_genes['test_sum'] = np.vectorize(test_sum)(go_genes['go_sequence'])
go_genes

t = experiment.loc[experiment['go_sequences'].str.contains('GO:0000003')]

In [60]:
def p_value(go_seq):
    t = experiment.loc[~experiment['go_sequences'].str.contains(go_seq)]
    sample_number = go_genes.loc[go_genes['go_sequence']==go_seq]['count'].values[0]
    test_sum = go_genes.loc[go_genes['go_sequence']==go_seq]['test_sum'].values[0]
    sums = []
    for i in range(1000):
        samples = np.random.choice(a=np.array(t['test_value']), size=sample_number)
        sample_sum = np.mean(samples)
        sums += [sample_sum]
    sums = np.array(sums)
    return np.sum(test_sum >= sums) / 1000



go_genes['p_value'] = np.vectorize(p_value)(go_genes['go_sequence'])

In [82]:
go_genes[['go_sequence', 'p_value']].to_csv('pvalues.csv')

In [61]:
go_genes

,go_sequence,genes,count,test_sum,p_value
0,GO:0000003,"WBGene00023826,WBGene00024356,WBGene00024943,W...",33,3.284391,0.167
1,GO:0000012,WBGene00041049,1,0.995454,0.484
2,GO:0000019,WBGene00035859,1,0.258124,0.140
3,GO:0000022,WBGene00026971,1,0.336241,0.178
4,GO:0000027,"WBGene00023936,WBGene00024087,WBGene00024572,W...",17,1.135907,0.099
...,...,...,...,...,...
2876,GO:2001253,WBGene00030176,1,1.708158,0.735
2877,GO:2001255,WBGene00033437,1,10.810034,0.921
2878,GO:2001256,WBGene00025899,1,6.333774,0.906
2879,GO:2001258,WBGene00036655,1,10.980771,0.909
2880,GO:2001294,WBGene00037538,1,2.137040,0.803